pcorless/icepdf

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/markup/MarkupAnnotationHandlerPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/PageComponentSelector.java
The view will still scroll to the annotation when an annotation is selected from the annotation panel.    
Fixes #22
=> GH-22 The page doesn't jump anymore when an annotation is selected

.gitignore, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/properties/BorderPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/attachment/AttachmentPanel.java
Also uses the last selected directory when the open file dialog is reopened due to an error.    
Depends on #27 
Fixes #21
=> Use FileDialog instead of JFileChooser

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/PersistentJCheckBoxMenuItem.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/search/SearchFilterButton.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/search/SearchPanel.java
Clicking on a menu item can send a NPE, at least when ICEpdf is integrated in an SWT project.
=> Fix persistent JCheckboxMenuItemUI

core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/Annotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/BlendComposite.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/Shapes.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/commands/BlendCompositeDrawCmd.java
The "java.lang.InternalError: not implemented yet" is ultimately related to how we paint annotations on top of the page content in the Viewer RI.  The main page content paints fine with BlendingComposite because we paint all this content to an buffer before painting the buffer the swing/awt canvas.  The trouble starts when we try and paint the annotation content on top of the page content.  The swing/awt canvas doesn't like the blendingComposite and fails to paint with some loud logging and missing annotation content.  
The trick with this PR is that we want to leave page painting unaffected, as BlendingComposites are pretty important part of our current transparency group support.  However BlendingComposites are uses sparingly for annotation and one typically only sees them for …
=> GH-118 fix errors painting annotations that use BlendComposite effect

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/TextMarkupAnnotationComponent.java
Potential fix for the text selection issues. 
- allows for fine grain text markup annotation selection. 
- added fallback code to to make sure we given a reasonable approximation for the contains calculation.
=> GH-168 fallback to annotation bounds if markup paths don't overlap.

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontType1C.java
Fixes issue finding some type1c glyphs in the font file.
=> GH-203 check encoding for code name before checking if glyph exists.

core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/Annotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/FreeTextAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/TextWidgetAnnotation.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java
I believe this issue was introduced when the new font library was integrated.  Basically some fonts like Type1 require an encoding to allow for glyph selection and in this particular case get a valid glyph width for layout.  
This PR will fix any layout issue when changing a free text annotations font (all squished up).  And a potential memory reference issue with open dialogs and saving an edited annotations properties.
=> GH-206 fixes layout issues when selecting free text annotation fonts

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java
GH-226
- update the save button command to fall back to saveAs if there are no document changes present.  
- Fairly sure this was the old 6.3 behaviour and can be helpful when the viewer is used as a component with no file menu to access 'Save as...'.
=> GH-226 save button command behaviour change. 

core/core-awt/src/main/java/org/icepdf/core/util/parser/content/AbstractContentParser.java, core/core-awt/src/main/java/org/icepdf/core/util/parser/content/ContentParser.java
GH-243
- this issue showed up years ago when a series of PDF was using a cm instead of tm to flip text.  To get around this issue I put in a horizontal flip as for the specific case.  
- this ticket is for a generator that is inserted in Do in a text block.   So I ended up using a similar flip technique and token handling inside a text block.  
- Still don't have enough clues to go on to how to deal with properly.  But qa passed so I'm going to merge and wait for another file to show up to shed more light on how to handle these elements.
=> GH-243 make adjustment for non-text operands in a text block

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/FontDescriptor.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontTrueType.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontType1.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZSimpleFont.java
- fixes a coordinate space error when getting the font descriptor's bbox and defers the conversion to java2d space.  
- use delta transform to apply the fontMatrix transform to the PDF rectangle points.
- adds caching the maxCharBounds value that can span deriveFont calls.
=> GH-245 address a coordinate space issue when calculating a glyphs bbox

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/MouseWheelListenerPageChanger.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/DocumentViewControllerImpl.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/TwoColumnPageView.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/TwoColumnPageViewLayout.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/TwoPageView.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/TwoPageViewLayout.java
- 7.1.0 was a rewrite of the page views to get the popup annotation to be draggable outside of a page. 
- for some reason I got in my head the left view type was a right to left page layout which it isn't. 
- this pr address the layout issues and odd pages numbers are correctly on the left when LEFT_VIEW is used when creating two page views.
=> Gh-279 left page view layout regressions

core/core-awt/src/main/java/org/icepdf/core/pobjects/Dictionary.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/HexStringObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/LiteralStringObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/PObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/Annotation.java, core/core-awt/src/main/java/org/icepdf/core/util/Library.java, core/core-awt/src/main/java/org/icepdf/core/util/parser/content/ContentParser.java, core/core-awt/src/main/java/org/icepdf/core/util/parser/object/Parser.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/FullUpdater.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/ArrayWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/BaseWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/DictionaryWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/HexStringObjectWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/LiteralStringWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/PObjectWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/StreamWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/TrailerWriter.java, core/core-awt/src/test/java/org/icepdf/core/util/updater/RewriteTest.java
Problem
- issues writing full document writes when document is encrypted. 
- incremental updates always encrypted the annotation edits on the fly storing the encrypted value, this can't be done for full writes.   This is further compounded by the fact that object coming out of compress Object streams have values that aren't enccrypted.  
- so we need to make sure all objects are unencrypted, no exception then we can write them all at once. 
Solution
- add parser hint to make sure we don't encrypt the /encrypt dictionary and trailer fileID. 
- normalized all the annotation class so we store values unencrypted. 
- make sure we escape encrypted string.
- update the parser and writer to keep track of the parent PObject so we have access the reference when encryption starts. 
-
=> GH-291 fixing encryption related problems during document rewrites. 

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/PageViewComponentImpl.java
Using Reference instead of annotation makes sure that the correct equality is used.
=> Fixes annotation to component in PageViewComponentImpl

core/core-awt/src/main/java/org/icepdf/core/pobjects/Document.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/DocumentBuilder.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/FullUpdater.java
- it's document in a few JDK bug tracks but the basic problem is there appears to be a file descriptor leak on Windows when using 
```
ByteBuffer mappedFileByteBuffer = documentFileChannel.map(
FileChannel.MapMode.READ_ONLY, 0, documentFileChannel.size());
```
Reworked the file copy to play more nicely with the windows JDK.
=> GH-323 fix file descriptor leak on window

core/core-awt/src/main/java/org/icepdf/core/pobjects/AbstractStringObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/Dictionary.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/HexStringObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/LiteralStringObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/PInfo.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/StringObject.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/actions/ActionFactory.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/actions/LaunchAction.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/actions/URIAction.java, core/core-awt/src/main/java/org/icepdf/core/util/Library.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/HexStringObjectWriter.java, core/core-awt/src/main/java/org/icepdf/core/util/updater/writeables/LiteralStringWriter.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PopupAnnotationComponent.java
- corrects an escape issue that was basically double escaping text on re-saves. 
- normalizing a bunch of the encryption handling of StringObjects
- fixes broken weak reference library cache.
=> GH-327 markup annotation content escaping

core/core-awt/src/main/java/org/icepdf/core/pobjects/HexStringObject.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/SelectionBoxHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/TextSelectionPageHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/MarkupGlueComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/TextMarkupAnnotationComponent.java
Allows text selection when markup annotation are present on the screen.
=> GH-336 allows text selection to work on text that is already covered by markup annotation

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/Type0Font.java
- a sample wasn't rendering correctly
- on closer inspection the strings were being parsed using the multi-byte code paths.   
- This is normal for CID font but after closer inspection of the font's cmap file there was a property /CMapName OneByteIdentityH that I had never seen before.  
- Adjusted parsing flags appropriately and the file renders correctly.  
- No regression in the QA suite and a few other files where fixed by this finding.
=> GH-340 fix encoding issues 

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingViewBuilder.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/widgets/AbstractColorButton.java
The spacing was increased with the original PR. I don't know if that was intentional, but if it wasn't, here is a quick fix to restore the more original look.
Also increases the width of the zoom and privacy comboboxes because the text was cut (at least on my machine).
=> GH-345 Restores original spacing between button and dropdown arrow in toolbar

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontType0.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontType2.java
Embedded Type2 fonts may have a default width for characters. These characters are not mentioned in the W-Tag and currently stored with a zero-width. When a string gets rendered, the characters are spaced by the stored width. If this is zero the current implementation assumes a width of 1.000. This leads to strange inter-word-spaces. Using the default width renderes the text correctly
=> GH-383 Using defaultWidth in ZFontType2.getAdvance

core/core-awt/src/main/java/org/icepdf/core/pobjects/structure/Indexer.java
Fixes #381 
This tries to exit the indexing loop if the position doesn't move.     
I'm not really sure it's the correct way to do it given my non-expertise in PDF indexing, so don't hesitate to tell me or modify the exit condition if needed.
=> GH-381 Exit indexing loop if previous position == position

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontTrueType.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontType1C.java
- fix a encoding issue which was preventing some FontType1c fonts from finding the correct glyph mapping
- Similarly for TrueType, added code to fall back on the fonts post script table if no other encoding find a mapping.
=> GH-386 fix two glyph selection issues

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/outline/OutlinesController.java
- puts outline edits behind a feature flag. 
- default is disabled or false. 
- will enable for version 7.3.0 release.
=> GH-237 put editable outlines behind a feature flag org.icepdf.viewer.outlineEdit.enabled

core/core-awt/src/main/java/org/icepdf/core/pobjects/Page.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/FreeTextAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/Shapes.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/TextSprite.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/AbstractText.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/GlyphText.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/LineText.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/PageText.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/WordText.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/structure/Indexer.java, core/core-awt/src/main/java/org/icepdf/core/util/parser/content/AbstractContentParser.java, core/core-awt/src/main/java/org/icepdf/core/util/parser/content/ContentParser.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/search/DocumentSearchControllerImpl.java
- long standing bug where text selection and searching can act wonky when a Page has a non zero rotation.   
- In such a case text is generally not layed out  int a left to right top down way and the text sorting code ends up putting in a whole bunch more line breaks and spaces then actually needed.
=> Gh-263 page rotatoin compensation when sorting text

pom.xml
- old ossrh system is shutting down at the end of June. 
- migrate publishing to the new servers and plugin.
=> GH-408 migrate from ossrh to maven central repo plugin.

core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/LineText.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/search/SearchFilterButton.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/DocumentViewControllerImpl.java
- addresses a really old but where text could be marked as white space when autospaces were inserted before the word. 
- this fixes a corner case where the word in question won't show up in a regex search. 
- fix a few UI state issues with the search filter button menuItems.
=> GH-410 fix word being flagged as whitespace

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/AbstractWorkerPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/NameJTree.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/layers/LayersTree.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/outline/OutlinesTree.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/signatures/SignaturesTree.java
- remove some jtree font size settings. 
- no default to default swing look and feel.
=> GH-417 remove hard code tree sizes and spacing, fallback on swing defaults

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/Type0Font.java
- add some protection to make sure we are dealing with a CompositeFont before casting.  
- user has reported a malformed file but no sample as of yet. 
- if I can get the sample file,  might be able to check if the returned FontDescriptor has a workable font.
=> GH-414 make sure we have a CompositeFont before proceeding

core/core-awt/src/main/java/org/icepdf/core/pobjects/acroform/signature/handlers/Pkcs11SignerHandler.java, viewer/viewer-awt/src/test/java/org/icepdf/signing/SigningTests.java
- SigningTest referenced a local cert which breaks the viewer build. 
- created cert specifically for test and added to test resources.
=> GH-436 fix cert signer path in test.

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/FontManager.java, core/core-awt/src/test/java/org/icepdf/core/pobjects/fonts/FontManagerTest.java
Adds a new system property to specify regex to filter out system fonts that will be read by the font manager.
=> GH-445 allow list for fontManager

viewer/viewer-awt/src/main/java/org/icepdf/ri/util/FontPropertiesManager.java
Adds a new system property org.icepdf.ri.util.FontPreferencesKey that allows the specification of the class path  that should be used for the user node when writing the preference file.  By default nothing changes but the system property can be used to specify a new class path where the preferences will be written.
=> GH-444 add a configurable for user node for the preference api

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/FontDescriptor.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/FontFactory.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/zfont/fontFiles/ZFontType1.java
- adds a cache for system fonts as per the suggestion of @volkerwahh 
- when a page(s) have a lot of fonts that fallback on font substitution then the cache kicks in. 
- this is particularly useful with acroforms where there could be 60 fields on a page and 60 instances of the same font. 
- anyways nice memory optimization
=> GH-440 font factory cache for loaded system fonts
