README.md, examples/readme.html, readme.html
Addition of readme.md and touched up the bundle readme to align with new home on github.
=> GH-1 documentation updates

.gitignore, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/util/Resources.java
and the exception message is sometimes empty, in this case use exception.toString
Fixes #10
=> Fix message formatting quote

.gitignore, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/properties/BorderPanel.java
Also adds a gitignore
Fixes #8
=> Fix border visible combobox

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle.properties
=> GH-24 Warns the user when they can't save to a directory

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java
=> GH-19 Reopens open dialog when a file other than pdf has been selected

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/CircleAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/HighLightAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/InkAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/LineAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/SquareAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/TextAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PopupAnnotationComponent.java
=> Fixes MouseWheel zoom on popup annotation

core/core-awt/src/main/java/org/icepdf/core/pobjects/Page.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/BorderStyle.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/fonts/FontHandlerPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/markup/MarkupAnnotationHandlerPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/signatures/SignaturesHandlerPanel.java
=> Fixes some bugs

.gitignore, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/properties/BorderPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/summary/AnnotationSummaryFrame.java, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_da.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_de.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_es.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_fi.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_fr.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_it.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_nl.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_no.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_pt.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_sv.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_zh_CN.properties, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle_zh_TW.properties
=> GH-35 Changes window title to [filename]

.gitignore, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/properties/BorderPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/DocumentViewControllerImpl.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/AbstractAnnotationComponent.java
=> GH-18 Allows deleting selected annotation with delete key

core/core-awt/src/main/java/org/icepdf/core/pobjects/fonts/FontFactory.java, core/core-awt/src/main/java/org/icepdf/core/util/content/ContentParserFactory.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/search/SearchFilterButton.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/search/SearchPanel.java
=> Allows not using NFont even if available

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PopupAnnotationComponent.java
Can't get master to build with the casting change on openJDK 11.  Need to double check this issue on 8.
=> GH-102 fix casting issue that was breaking build

core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/Annotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/PolyAnnotation.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PolyLineAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PolygonAnnotationComponent.java
Basic boiler plate class to support parsing of Polygon and PolyLine annotations types.
=> GH-142 added basic PolyAnnotation class

core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/FreeTextAnnotation.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/FreeTextAnnotationComponent.java
Combined PR of for initial paint issue of free text annotations.  Based on https://github.com/pcorless/icepdf/pull/137 with further work to the component
=> GH-136 fix some repaint issues when displaying free text annotations.

core/core-awt/src/main/java/org/icepdf/core/pobjects/Page.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/AbstractWidgetAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/Annotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/MarkupAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/MarkupGlueAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/PopupAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/TextMarkupAnnotation.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/print/PrintHelper.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/print/PrintHelperImpl.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/AbstractAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/MarkupGlueComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PopupAnnotationComponent.java
- respect font size set in viewer when printing
- update shrink to fit takes into account popup annotation locations when scaling a page to fit a paper size.
=> GH-173 popup annotation printing tweaks

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/InkAnnotationHandler.java
- allows the creation of an ink annotation with multiple paths. 
- makes it easier for users with stylus type input to draw more complex ink annotations.
=> GH-295 add basic multi-path support to ink annotation

core/core-awt/src/main/java/org/icepdf/core/pobjects/FileSpecification.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/attachment/AttachmentPanel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/attachment/FileTableModel.java
=> GH-308 Checks for null embeddedFileStream

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/MarkupAnnotationPopupMenu.java, viewer/viewer-awt/src/main/resources/org/icepdf/ri/resources/MessageBundle.properties
=> GH-324 Adds copy highlighted text

core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/Annotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/ButtonWidgetAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/ChoiceWidgetAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/FreeTextAnnotation.java, core/core-awt/src/main/java/org/icepdf/core/pobjects/annotations/TextWidgetAnnotation.java
=> GH-25 Pass isNew to stateManager in various methods

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/CircleAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/HighLightAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/InkAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/LineAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/SquareAnnotationHandler.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/tools/TextAnnotationHandler.java
- makes sure popup annotation component are created at the same size relative to the page size/zoom level.
=> GH-328 normalize popup size relative to page size

.gitignore, core/core-awt/src/main/java/org/icepdf/core/CombinedMemento.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/MyAnnotationCallback.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/UndoCaretaker.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/utility/annotation/markup/FindMarkupAnnotationTask.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/AbstractDocumentViewModel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/DocumentViewControllerImpl.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/DocumentViewModel.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/PageViewComponentImpl.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/AbstractAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/AnnotationState.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/InkAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/LineAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/MarkupAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PopupAnnotationComponent.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/PopupState.java
Closes #34       
Supports only annotation create, delete and move for now.
=> GH-34 Implements undo/redo

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/print/PrintHelper.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/print/PrintHelperImpl.java
GH-356
- rejig PrinterHelper to implement Printable
- should allow allow for better mixing of printable document types.
=> GH-356 update PrintHelper to implement Printable

core/core-awt/src/main/java/org/icepdf/core/pobjects/graphics/text/PageText.java
=> GH-359 Uses getPageLines in PageText#toString

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java
- reassign the binocular icon to activate the advance search utility pane
=> GH-393 make sure the toolbar binocular searchButton activates advanced search

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/SwingController.java
- brings back the old toggle behaviour of the binocular toolbar button.  
-
=> GH-393 make binoculars button toggle advance search and utility pane visiblity

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/FreeTextAnnotationComponent.java
=> GH-424 make sure we don't set a null awt font when setting up FreeTextAnnotationComponents

viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/DocumentViewControllerImpl.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/views/annotations/summary/AnnotationSummaryFrame.java, viewer/viewer-awt/src/main/java/org/icepdf/ri/common/widgets/RgbColorChooser.java
- fix a few centering and parent reference issue with dialogs launched from the viewer component
-  make sure signature appearance callback gets created. 
- title null pointer with annotation summary launched from component
=> GH-431 clean up viewer component dialogs
